USE javaproject;

DELIMITER //
CREATE PROCEDURE GetMapByName(IN mapName VARCHAR(255))
BEGIN
    SELECT line FROM map WHERE name1 = mapName;
END //
DELIMITER ;

CREATE TABLE map (
  name1 VARCHAR(255) NOT NULL,
   line VARCHAR(255) NOT NULL
);

INSERT INTO map(name1, line)
VALUES
    ('map1', '21'),
    ('map1', '11'),
    ('map1', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map1', 'WWGPGGDDDDDDGGGGGGGGW'),
    ('map1', 'WWGGGGGDGGGGDGGGGGGWW'),
    ('map1', 'WGGGGGGDGGGGDGGGGGGGW'),
    ('map1', 'WWWWGGDGGGGDGGGGGGGGW'),
    ('map1', 'WGGGGGDGGGGDGGGGGGGGW'),
    ('map1', 'WGGGGDGGGWWGGDGGGGEGW'),
    ('map1', 'WGGGGGGGGGGDGGGGWWWWW'),
    ('map1', 'WGGGGGDGGGGDGGGGGRRGW'),
    ('map1', 'WGGGGGGGGGGDGGGGGRGGW'),
    ('map1', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map2', '21'),
    ('map2', '11'),
    ('map2', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map2', 'WGGRRGGGWGGGGRGRRGGGW'),
    ('map2', 'WWGGGGDGRWWWWRGGRGWWW'),
    ('map2', 'WGGRGDGGGGWWRGGRGGGGW'),
    ('map2', 'WGGRWGGGDGWGWRGGWRWRW'),
    ('map2', 'WRRRWRGGRGWGWRGGWRGGW'),
    ('map2', 'WGGGGWGGGGGGGGWGGGWRW'),
    ('map2', 'WRVVWGWGDGGGGGGGVVGEW'),
    ('map2', 'WWVVGGGWGGGDGGGWDVGGW'),
    ('map2', 'WRRVVVVVWRGGRGRGGGRRW'),
    ('map2', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map3', '21'),
    ('map3', '11'),
    ('map3', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map3', 'WGGGWWWWWWWWWWWWWWWWW'),
    ('map3', 'WGGGVGGGGGDGRGGGGGGGW'),
    ('map3', 'WGRGGGGGGGGGDGGGGGGGW'),
    ('map3', 'WGGGGDGGGGGGGGDGGGGGW'),
    ('map3', 'WGGVVGGGGGGGGGRGGGGEW'),
    ('map3', 'WGRVBGGDGGGGGRRGGGGVW'),
    ('map3', 'WGGRRGGGGGGGGGRRGGGGW'),
    ('map3', 'WWWWWWWVVGWWWWWWWWWWW'),
    ('map3', 'WGGGRGGDGVGGRGRGGVVGW'),
    ('map3', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map4', '21'),
    ('map4', '11'),
    ('map4', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map4', 'GGGGGGGRGGRGGGGGGGGGG'),
    ('map4', 'RRGGGGGGGGGGGGGGGGGGG'),
    ('map4', 'RRRGGGGVBGGGGGGVBGGGG'),
    ('map4', 'RRGGVGGGVVGGGGGGVVGGG'),
    ('map4', 'GGGGGGGGGGGGGGGGGGGGG'),
    ('map4', 'GGGGGGDGGGGGGGRGGGGEG'),
    ('map4', 'WGGGGGGGGDGGGGGGGGGGG'),
    ('map4', 'GGGGGGGGGRGGGGGGGGGGG'),
    ('map4', 'GGGGGGGGGGRGGGDGGGGGG'),
    ('map4', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map5', '21'),
    ('map5', '11'),
    ('map5', 'WWWWWWWWWWWWWWWWWWWWW'),
    ('map5', 'WGGGGGGGGGGGGGGGGGGGW'),
    ('map5', 'WGGGGWWWWWWWWWWWWWWWW'),
    ('map5', 'WVVVVGRGGGGGGGGRGGGGW'),
    ('map5', 'WGGVVRGGGGGGGGGGVGGGW'),
    ('map5', 'WGGGVVBGGRGGGGGVBVGGW'),
    ('map5', 'WGGVVGGGGGGGDGGGGVGGW'),
    ('map5', 'WGGRGGGGGGGGGGGGGGGGW'),
    ('map5', 'WGGGGGGGVVGGGGGGDGGEW'),
    ('map5', 'WRRGVGGGVBGGGGGGGGGGW'),
    ('map5', 'WWWWWWWWWWWWWWWWWWWWW')